import { uniqueNamesGenerator } from "unique-names-generator"

// ─── RPG-themed word lists ────────────────────────────────────────────────────

const rpgAdjectives = [
  "ancient",
  "cursed",
  "sacred",
  "forbidden",
  "ethereal",
  "blazing",
  "shadow",
  "arcane",
  "dark",
  "holy",
  "crimson",
  "iron",
  "fallen",
  "lost",
  "silent",
  "burning",
  "frozen",
  "golden",
  "silver",
  "jade",
  "obsidian",
  "void",
  "astral",
  "unholy",
  "sunken",
  "shattered",
  "ruined",
  "haunted",
  "spectral",
  "infernal",
  "divine",
  "elder",
  "phantom",
  "wrathful",
  "venomous",
]

const rpgCreatures = [
  "dragon",
  "lich",
  "paladin",
  "wraith",
  "wizard",
  "ranger",
  "bard",
  "rogue",
  "cleric",
  "ogre",
  "troll",
  "goblin",
  "vampire",
  "phoenix",
  "griffon",
  "wyvern",
  "specter",
  "revenant",
  "hydra",
  "basilisk",
  "manticore",
  "golem",
  "minotaur",
  "chimera",
  "sphinx",
  "warlock",
  "druid",
]

const rpgPlaces = [
  "keep",
  "spire",
  "realm",
  "dungeon",
  "citadel",
  "vault",
  "forge",
  "sanctum",
  "crypt",
  "temple",
  "tower",
  "abyss",
  "throne",
  "bastion",
  "cavern",
  "vale",
  "grove",
  "shrine",
  "labyrinth",
  "stronghold",
  "lair",
  "hollow",
  "fortress",
  "archive",
  "nexus",
]

// ─── Generator ────────────────────────────────────────────────────────────────

export function generateGameSlug(): string {
  return uniqueNamesGenerator({
    dictionaries: [rpgAdjectives, rpgCreatures, rpgPlaces],
    separator: "-",
    style: "lowerCase",
  })
}
